import fs from "node:fs/promises";
import path from "node:path";
import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { audit } from "../lib/audit.js";
import { ensureParent, resolvePath } from "../lib/paths.js";

const out=(tool:string,data:unknown)=>({content:[{type:"text" as const,text:JSON.stringify(data)}],structuredContent:{ok:true,tool,data}});
const globRx=(g:string)=>new RegExp("^"+g.replace(/[.+^${}()|[\]\\]/g,"\\$&").replace(/\*\*/g,"§§").replace(/\*/g,"[^/\\\\]*").replace(/§§/g,".*").replace(/\?/g,".")+"$","i");
async function walk(root:string,max=1000){const files:string[]=[];const q=[root];while(q.length&&files.length<max){const d=q.shift()!;let es;try{es=await fs.readdir(d,{withFileTypes:true})}catch{continue}for(const e of es){const p=path.join(d,e.name);if(e.isDirectory()){if(![".git","node_modules","Binaries","Intermediate","DerivedDataCache"].includes(e.name))q.push(p)}else if(e.isFile())files.push(p);if(files.length>=max)break}}return files}

export function registerFileTools(server:McpServer){
 server.registerTool("read_text_file",{description:"Read a UTF-8 text file.",inputSchema:{path:z.string(),offset:z.number().int().min(1).optional(),limit:z.number().int().min(1).max(5000).optional()}},async({path:p,offset=1,limit=1000})=>{const f=await resolvePath(p);const lines=(await fs.readFile(f,"utf8")).split(/\r?\n/);const data={path:f,content:lines.slice(offset-1,offset-1+limit).join("\n"),offset,lines:Math.min(limit,Math.max(0,lines.length-offset+1))};await audit("read_text_file","ok",{path:f});return out("read_text_file",data)});
 server.registerTool("write_file",{description:"Write UTF-8 text to a file.",inputSchema:{path:z.string(),content:z.string()}},async({path:p,content})=>{const f=await resolvePath(p);await ensureParent(f);await fs.writeFile(f,content,"utf8");await audit("write_file","ok",{path:f,bytes:Buffer.byteLength(content)});return out("write_file",{path:f,bytes:Buffer.byteLength(content)})});
 server.registerTool("edit_file",{description:"Replace exact text in one file.",inputSchema:{path:z.string(),old_text:z.string(),new_text:z.string(),replace_all:z.boolean().optional()}},async({path:p,old_text,new_text,replace_all=false})=>{const f=await resolvePath(p);const s=await fs.readFile(f,"utf8");if(!s.includes(old_text))throw new Error("old_text not found");const n=replace_all?s.split(old_text).join(new_text):s.replace(old_text,new_text);await fs.writeFile(f,n,"utf8");await audit("edit_file","ok",{path:f});return out("edit_file",{path:f,changed:true})});
 server.registerTool("list_directory",{description:"List one directory.",inputSchema:{path:z.string()}},async({path:p})=>{const d=await resolvePath(p);const es=await fs.readdir(d,{withFileTypes:true});const data={path:d,entries:es.slice(0,500).map(e=>({name:e.name,type:e.isDirectory()?"directory":"file"}))};await audit("list_directory","ok",{path:d,count:data.entries.length});return out("list_directory",data)});
 server.registerTool("glob",{description:"Find files by bounded glob under a directory.",inputSchema:{path:z.string(),pattern:z.string(),max_results:z.number().int().min(1).max(500).optional()}},async({path:p,pattern,max_results=100})=>{const root=await resolvePath(p);const rx=globRx(pattern);const files=await walk(root,5000);const matches=files.filter(f=>rx.test(path.relative(root,f).replace(/\\/g,"/"))).slice(0,max_results);await audit("glob","ok",{path:root,pattern,count:matches.length});return out("glob",{path:root,pattern,matches})});
 server.registerTool("grep",{description:"Search text files with a 15 second deadline.",inputSchema:{path:z.string(),pattern:z.string(),glob:z.string().optional(),case_insensitive:z.boolean().optional(),max_results:z.number().int().min(1).max(500).optional()}},async({path:p,pattern,glob="**/*",case_insensitive=false,max_results=200})=>{const root=await resolvePath(p);const rx=new RegExp(pattern,case_insensitive?"i":"");const grx=globRx(glob);const deadline=Date.now()+15000;const files=(await walk(root,5000)).filter(f=>grx.test(path.relative(root,f).replace(/\\/g,"/")));const matches:any[]=[];for(const f of files){if(Date.now()>deadline)break;let s;try{s=await fs.readFile(f,"utf8")}catch{continue}const ls=s.split(/\r?\n/);for(let i=0;i<ls.length;i++){if(rx.test(ls[i])){matches.push({path:f,line:i+1,text:ls[i].slice(0,1000)});if(matches.length>=max_results)break}}if(matches.length>=max_results)break}await audit("grep","ok",{path:root,pattern,count:matches.length});return out("grep",{path:root,pattern,matches,truncated:matches.length>=max_results||Date.now()>deadline})});
}
