import { spawn } from "node:child_process";
import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { getMcpActorId } from "../lib/mcp-request-context.js";
import { audit } from "../lib/audit.js";
import { safeChildEnv } from "../lib/safe-env.js";

const BUSY=/^BUSY - (\S+)\s*([\s\S]*?) :: ([\s\S]+)$/;
const out=(tool:string,data:unknown,ok=true)=>({content:[{type:"text" as const,text:JSON.stringify(data)}],structuredContent:{ok,tool,data}});
const actor=()=>getMcpActorId()||"actor-unknown";
function gh(args:string[],cwd=process.cwd()){return new Promise<{stdout:string,stderr:string,exit_code:number|null}>((resolve,reject)=>{const p=spawn("gh",args,{cwd,windowsHide:true,env:safeChildEnv()});let stdout="",stderr="";p.stdout.on("data",d=>stdout+=d);p.stderr.on("data",d=>stderr+=d);p.on("error",reject);p.on("close",code=>resolve({stdout:stdout.trim(),stderr:stderr.trim(),exit_code:code}))})}
async function issue(repo:string,n:number){const r=await gh(["issue","view",String(n),"--repo",repo,"--json","number,title,updatedAt,url,state"]);if(r.exit_code!==0)throw new Error(r.stderr||"gh issue view failed");return JSON.parse(r.stdout)}
export function registerGithubTools(server:McpServer){
 server.registerTool("actor_status",{description:"Return the current MCP actor id.",inputSchema:{}},async()=>out("actor_status",{actor_id:actor()}));
 server.registerTool("issue_list",{description:"List open GitHub issues.",inputSchema:{repo:z.string(),limit:z.number().int().min(1).max(200).optional()}},async({repo,limit=50})=>{const r=await gh(["issue","list","--repo",repo,"--state","open","--limit",String(limit),"--json","number,title,updatedAt,url"]);await audit("issue_list",r.exit_code===0?"ok":"error",{repo,exit_code:r.exit_code});if(r.exit_code!==0)throw new Error(r.stderr);return out("issue_list",{repo,issues:JSON.parse(r.stdout||"[]")})});
 server.registerTool("issue_comment",{description:"Add a GitHub issue comment.",inputSchema:{repo:z.string(),issue:z.number().int().positive(),body:z.string()}},async({repo,issue,body})=>{const r=await gh(["issue","comment",String(issue),"--repo",repo,"--body",body]);await audit("issue_comment",r.exit_code===0?"ok":"error",{repo,issue,exit_code:r.exit_code});if(r.exit_code!==0)throw new Error(r.stderr);return out("issue_comment",{repo,issue,commented:true})});
 server.registerTool("issue_close",{description:"Close a GitHub issue.",inputSchema:{repo:z.string(),issue:z.number().int().positive()}},async({repo,issue})=>{const r=await gh(["issue","close",String(issue),"--repo",repo]);await audit("issue_close",r.exit_code===0?"ok":"error",{repo,issue,exit_code:r.exit_code});if(r.exit_code!==0)throw new Error(r.stderr);return out("issue_close",{repo,issue,closed:true})});
 server.registerTool("busy_list",{description:"List GitHub issues marked BUSY.",inputSchema:{repo:z.string()}},async({repo})=>{const r=await gh(["issue","list","--repo",repo,"--state","open","--limit","200","--search","BUSY in:title","--json","number,title,updatedAt,url"]);if(r.exit_code!==0)throw new Error(r.stderr);const now=Date.now(),busy=JSON.parse(r.stdout||"[]").map((x:any)=>{const m=String(x.title).match(BUSY);return m?{issue:x.number,who:m[1],what:m[2].trim(),title:m[3],updated_at:x.updatedAt,idle_seconds:Math.max(0,Math.round((now-Date.parse(x.updatedAt))/1000)),url:x.url}:null}).filter(Boolean);await audit("busy_list","ok",{repo,count:busy.length});return out("busy_list",{repo,busy})});
 server.registerTool("busy_claim",{description:"Mark an issue BUSY for the current MCP actor if it is not owned by another actor.",inputSchema:{repo:z.string(),issue:z.number().int().positive(),what:z.string().min(1)}},async({repo,issue:n,what})=>{const x=await issue(repo,n),m=String(x.title).match(BUSY),who=actor();if(m&&m[1]!==who){const data={repo,issue:n,claimed:false,collision:true,current_holder:m[1],current_what:m[2].trim(),title:m[3]};await audit("busy_claim","blocked",data);return out("busy_claim",data,false)}const base=m?m[3]:x.title,next=`BUSY - ${who} ${what.trim()} :: ${base}`;const r=await gh(["issue","edit",String(n),"--repo",repo,"--title",next]);if(r.exit_code!==0)throw new Error(r.stderr);await audit("busy_claim","ok",{repo,issue:n,who});return out("busy_claim",{repo,issue:n,claimed:true,who,title:next})});
 server.registerTool("busy_release",{description:"Clear the current actor's BUSY marker.",inputSchema:{repo:z.string(),issue:z.number().int().positive()}},async({repo,issue:n})=>{const x=await issue(repo,n),m=String(x.title).match(BUSY),who=actor();if(!m)return out("busy_release",{repo,issue:n,released:false,reason:"not busy"});if(m[1]!==who){const data={repo,issue:n,released:false,reason:"owned by another actor",current_holder:m[1]};await audit("busy_release","blocked",data);return out("busy_release",data,false)}const r=await gh(["issue","edit",String(n),"--repo",repo,"--title",m[3]]);if(r.exit_code!==0)throw new Error(r.stderr);await audit("busy_release","ok",{repo,issue:n,who});return out("busy_release",{repo,issue:n,released:true,who,title:m[3]})});
}
