import { spawn } from "node:child_process";
import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { audit } from "../lib/audit.js";

const procs=new Map<string,{child:any,stdout:string,stderr:string,command:string,cwd:string}>();
function safeEnv(){const e:any={};const deny=/(TOKEN|SECRET|PASSWORD|CREDENTIAL|COOKIE|API[_-]?KEY|AUTH|OPENAI|GITHUB|GH_|ANTHROPIC|AZURE|AWS|GOOGLE|TAILSCALE|CLOUDFLARE|NVIDIA|HUGGING|HF_|MCP_)/i;for(const[k,v]of Object.entries(process.env))if(v!==undefined&&!deny.test(k))e[k]=v;return {...e,CI:"true",PAGER:"cat",GIT_PAGER:"cat",NO_COLOR:"1"}}
const out=(tool:string,data:unknown,ok=true)=>({content:[{type:"text" as const,text:JSON.stringify(data)}],structuredContent:{ok,tool,data}});
function run(command:string,cwd:string,timeoutMs:number){return new Promise<{stdout:string,stderr:string,exit_code:number|null,timed_out:boolean}>((resolve,reject)=>{const child=spawn("powershell.exe",["-NoProfile","-NonInteractive","-ExecutionPolicy","Bypass","-Command",command],{cwd,windowsHide:true,env:safeEnv()});let stdout="",stderr="",done=false;const t=setTimeout(()=>{if(done)return;done=true;spawn("taskkill",["/PID",String(child.pid),"/T","/F"],{windowsHide:true});resolve({stdout,stderr,exit_code:null,timed_out:true})},timeoutMs);child.stdout.on("data",d=>stdout+=d);child.stderr.on("data",d=>stderr+=d);child.on("error",reject);child.on("close",code=>{if(done)return;done=true;clearTimeout(t);resolve({stdout:stdout.trim(),stderr:stderr.trim(),exit_code:code,timed_out:false})})})}
export function registerShellTools(server:McpServer,defaultCwd:string){
 server.registerTool("run_command",{description:"Run one bounded PowerShell command.",inputSchema:{command:z.string(),working_directory:z.string().optional(),timeout_seconds:z.number().int().min(1).max(120).optional()}},async({command,working_directory=defaultCwd,timeout_seconds=120})=>{const r=await run(command,working_directory,timeout_seconds*1000);await audit("run_command",r.exit_code===0&&!r.timed_out?"ok":"error",{cwd:working_directory,exit_code:r.exit_code,timed_out:r.timed_out});return out("run_command",{...r,cwd:working_directory},r.exit_code===0&&!r.timed_out)});
 server.registerTool("start_process",{description:"Start a background PowerShell command.",inputSchema:{command:z.string(),working_directory:z.string().optional()}},async({command,working_directory=defaultCwd})=>{const child=spawn("powershell.exe",["-NoProfile","-NonInteractive","-ExecutionPolicy","Bypass","-Command",command],{cwd:working_directory,windowsHide:true,env:safeEnv()});const id=`${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`, item={child,stdout:"",stderr:"",command,cwd:working_directory};procs.set(id,item);child.stdout.on("data",d=>item.stdout=(item.stdout+d).slice(-400000));child.stderr.on("data",d=>item.stderr=(item.stderr+d).slice(-400000));await audit("start_process","ok",{id,pid:child.pid,cwd:working_directory});return out("start_process",{id,pid:child.pid,cwd:working_directory})});
 server.registerTool("process_status",{description:"Show background process state.",inputSchema:{id:z.string().optional()}},async({id})=>out("process_status",{processes:[...procs.entries()].filter(([k])=>!id||k===id).map(([k,p])=>({id:k,pid:p.child.pid,running:p.child.exitCode===null,exit_code:p.child.exitCode,command:p.command,cwd:p.cwd}))}));
 server.registerTool("process_output",{description:"Read bounded background process output.",inputSchema:{id:z.string(),tail_chars:z.number().int().min(100).max(60000).optional()}},async({id,tail_chars=20000})=>{const p=procs.get(id);if(!p)throw new Error("unknown process");return out("process_output",{id,stdout:p.stdout.slice(-tail_chars),stderr:p.stderr.slice(-tail_chars),running:p.child.exitCode===null,exit_code:p.child.exitCode})});
 server.registerTool("stop_process",{description:"Stop a background process started by this MCP.",inputSchema:{id:z.string()}},async({id})=>{const p=procs.get(id);if(!p)throw new Error("unknown process");spawn("taskkill",["/PID",String(p.child.pid),"/T","/F"],{windowsHide:true});await audit("stop_process","ok",{id,pid:p.child.pid});return out("stop_process",{id,stopping:true})});
}

